import Head from 'next/head';
import { Inter } from 'next/font/google';
import Sidebar from '../components/Sidebar';
import Feed from '@/components/Feed';
import Widgets from '@/components/Widgets';

const inter = Inter({ subsets: ['latin'] })

export default function Home({newsResults}) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto max-w-7xl ">

          
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        <Feed />

        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} />
        {/* Modal */}
      </main>
    </>
  )
}


// https://saurav.tech/NewsAPI/top-headlines/category/bussiness/us.json

export const getServerSideProps = async() => {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());
  return{
    props:{
      newsResults,
    }
  }
}